# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0010_auto_20151227_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='address1',
            field=models.CharField(blank=True, default=b'', help_text=b'First street address of this site', max_length=50),
        ),
    ]
