# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0011_auto_20160115_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='address1',
            field=models.CharField(default=b'', help_text=b'First street address of this site', max_length=50),
        ),
        migrations.AlterField(
            model_name='site',
            name='county',
            field=models.CharField(blank=True, default=b'', help_text=b'County where site is located', max_length=50),
        ),
    ]
